[package]
name = "jsparser"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["blocking"] }
wasm-bindgen = "0.2.95"

[lib]
crate-type = ["cdylib"]

[profile.release]
# panic = "abort"
panic = "unwind"
lto = true
# opt-level = 's'
opt-level = "z"
