[package]
name = "jsparser"
version = "0.1.0"
edition = "2021"

[dependencies]
wasm-bindgen = "0.2.95"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]

[profile.release]
# panic = "abort"
panic = "unwind"
lto = true
# opt-level = 's'
opt-level = "z"
